/* tslint:disable */
/* eslint-disable */
/**
 * Data Analyst API
 * API for the Data Analyst project.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DataFileSessionStatus = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type DataFileSessionStatus = typeof DataFileSessionStatus[keyof typeof DataFileSessionStatus];


export function instanceOfDataFileSessionStatus(value: any): boolean {
    for (const key in DataFileSessionStatus) {
        if (Object.prototype.hasOwnProperty.call(DataFileSessionStatus, key)) {
            if (DataFileSessionStatus[key as keyof typeof DataFileSessionStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DataFileSessionStatusFromJSON(json: any): DataFileSessionStatus {
    return DataFileSessionStatusFromJSONTyped(json, false);
}

export function DataFileSessionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataFileSessionStatus {
    return json as DataFileSessionStatus;
}

export function DataFileSessionStatusToJSON(value?: DataFileSessionStatus | null): any {
    return value as any;
}

