/* tslint:disable */
/* eslint-disable */
/**
 * Data Analyst API
 * API for the Data Analyst project.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GraphModel
 */
export interface GraphModel {
    /**
     * 
     * @type {string}
     * @memberof GraphModel
     */
    graphName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GraphModel
     */
    xAxis?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GraphModel
     */
    xAxisName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GraphModel
     */
    yAxis?: number;
    /**
     * 
     * @type {string}
     * @memberof GraphModel
     */
    yAxisName?: string | null;
}

/**
 * Check if a given object implements the GraphModel interface.
 */
export function instanceOfGraphModel(value: object): value is GraphModel {
    return true;
}

export function GraphModelFromJSON(json: any): GraphModel {
    return GraphModelFromJSONTyped(json, false);
}

export function GraphModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphModel {
    if (json == null) {
        return json;
    }
    return {
        
        'graphName': json['graphName'] == null ? undefined : json['graphName'],
        'xAxis': json['xAxis'] == null ? undefined : json['xAxis'],
        'xAxisName': json['xAxisName'] == null ? undefined : json['xAxisName'],
        'yAxis': json['yAxis'] == null ? undefined : json['yAxis'],
        'yAxisName': json['yAxisName'] == null ? undefined : json['yAxisName'],
    };
}

export function GraphModelToJSON(value?: GraphModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'graphName': value['graphName'],
        'xAxis': value['xAxis'],
        'xAxisName': value['xAxisName'],
        'yAxis': value['yAxis'],
        'yAxisName': value['yAxisName'],
    };
}

