/* tslint:disable */
/* eslint-disable */
/**
 * Data Analyst API
 * API for the Data Analyst project.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KPIModel
 */
export interface KPIModel {
    /**
     * 
     * @type {string}
     * @memberof KPIModel
     */
    kpiName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof KPIModel
     */
    last30Days?: number;
    /**
     * 
     * @type {number}
     * @memberof KPIModel
     */
    last90Days?: number;
    /**
     * 
     * @type {number}
     * @memberof KPIModel
     */
    last3MonthsAverage?: number;
}

/**
 * Check if a given object implements the KPIModel interface.
 */
export function instanceOfKPIModel(value: object): value is KPIModel {
    return true;
}

export function KPIModelFromJSON(json: any): KPIModel {
    return KPIModelFromJSONTyped(json, false);
}

export function KPIModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): KPIModel {
    if (json == null) {
        return json;
    }
    return {
        
        'kpiName': json['kpiName'] == null ? undefined : json['kpiName'],
        'last30Days': json['last30Days'] == null ? undefined : json['last30Days'],
        'last90Days': json['last90Days'] == null ? undefined : json['last90Days'],
        'last3MonthsAverage': json['last3MonthsAverage'] == null ? undefined : json['last3MonthsAverage'],
    };
}

export function KPIModelToJSON(value?: KPIModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'kpiName': value['kpiName'],
        'last30Days': value['last30Days'],
        'last90Days': value['last90Days'],
        'last3MonthsAverage': value['last3MonthsAverage'],
    };
}

