/* tslint:disable */
/* eslint-disable */
/**
 * Data Analyst API
 * API for the Data Analyst project.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MeUserDto } from './MeUserDto';
import {
    MeUserDtoFromJSON,
    MeUserDtoFromJSONTyped,
    MeUserDtoToJSON,
} from './MeUserDto';

/**
 * 
 * @export
 * @interface MeDto
 */
export interface MeDto {
    /**
     * Whether the user is authenticate or not
     * @type {boolean}
     * @memberof MeDto
     */
    isAuthenticated?: boolean;
    /**
     * 
     * @type {MeUserDto}
     * @memberof MeDto
     */
    user?: MeUserDto;
}

/**
 * Check if a given object implements the MeDto interface.
 */
export function instanceOfMeDto(value: object): value is MeDto {
    return true;
}

export function MeDtoFromJSON(json: any): MeDto {
    return MeDtoFromJSONTyped(json, false);
}

export function MeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'isAuthenticated': json['isAuthenticated'] == null ? undefined : json['isAuthenticated'],
        'user': json['user'] == null ? undefined : MeUserDtoFromJSON(json['user']),
    };
}

export function MeDtoToJSON(value?: MeDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'isAuthenticated': value['isAuthenticated'],
        'user': MeUserDtoToJSON(value['user']),
    };
}

