/* tslint:disable */
/* eslint-disable */
/**
 * Data Analyst API
 * API for the Data Analyst project.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeUserDto
 */
export interface MeUserDto {
    /**
     * The user's Google Id
     * @type {string}
     * @memberof MeUserDto
     */
    googleId?: string | null;
    /**
     * The user's email address
     * @type {string}
     * @memberof MeUserDto
     */
    email?: string | null;
    /**
     * The user's name
     * @type {string}
     * @memberof MeUserDto
     */
    name?: string | null;
    /**
     * The user's profile picture
     * @type {string}
     * @memberof MeUserDto
     */
    profilePictureUrl?: string | null;
}

/**
 * Check if a given object implements the MeUserDto interface.
 */
export function instanceOfMeUserDto(value: object): value is MeUserDto {
    return true;
}

export function MeUserDtoFromJSON(json: any): MeUserDto {
    return MeUserDtoFromJSONTyped(json, false);
}

export function MeUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'googleId': json['googleId'] == null ? undefined : json['googleId'],
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'profilePictureUrl': json['profilePictureUrl'] == null ? undefined : json['profilePictureUrl'],
    };
}

export function MeUserDtoToJSON(value?: MeUserDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'googleId': value['googleId'],
        'email': value['email'],
        'name': value['name'],
        'profilePictureUrl': value['profilePictureUrl'],
    };
}

