/* tslint:disable */
/* eslint-disable */
/**
 * Data Analyst API
 * API for the Data Analyst project.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartGenerationDto
 */
export interface StartGenerationDto {
    /**
     * 
     * @type {string}
     * @memberof StartGenerationDto
     */
    filename?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof StartGenerationDto
     */
    initialFileHasHeaders?: boolean;
}

/**
 * Check if a given object implements the StartGenerationDto interface.
 */
export function instanceOfStartGenerationDto(value: object): value is StartGenerationDto {
    return true;
}

export function StartGenerationDtoFromJSON(json: any): StartGenerationDto {
    return StartGenerationDtoFromJSONTyped(json, false);
}

export function StartGenerationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartGenerationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'filename': json['filename'] == null ? undefined : json['filename'],
        'initialFileHasHeaders': json['initialFileHasHeaders'] == null ? undefined : json['initialFileHasHeaders'],
    };
}

export function StartGenerationDtoToJSON(value?: StartGenerationDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'filename': value['filename'],
        'initialFileHasHeaders': value['initialFileHasHeaders'],
    };
}

