/* tslint:disable */
/* eslint-disable */
/**
 * Data Analyst API
 * API for the Data Analyst project.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GraphModel,
  KPIModel,
  ProblemDetails,
} from '../models/index';
import {
    GraphModelFromJSON,
    GraphModelToJSON,
    KPIModelFromJSON,
    KPIModelToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface ApiGraphingGetGraphsGetRequest {
    dataSessionId?: string;
}

export interface ApiGraphingGetKPIGraphsGetRequest {
    dataSessionId?: string;
}

/**
 * 
 */
export class GraphingApi extends runtime.BaseAPI {

    /**
     */
    async apiGraphingGetGraphsGetRaw(requestParameters: ApiGraphingGetGraphsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: Array<GraphModel>; }>> {
        const queryParameters: any = {};

        if (requestParameters['dataSessionId'] != null) {
            queryParameters['dataSessionId'] = requestParameters['dataSessionId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Graphing/GetGraphs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async apiGraphingGetGraphsGet(requestParameters: ApiGraphingGetGraphsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: Array<GraphModel>; }> {
        const response = await this.apiGraphingGetGraphsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiGraphingGetKPIGraphsGetRaw(requestParameters: ApiGraphingGetKPIGraphsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<KPIModel>>> {
        const queryParameters: any = {};

        if (requestParameters['dataSessionId'] != null) {
            queryParameters['dataSessionId'] = requestParameters['dataSessionId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Graphing/GetKPIGraphs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(KPIModelFromJSON));
    }

    /**
     */
    async apiGraphingGetKPIGraphsGet(requestParameters: ApiGraphingGetKPIGraphsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<KPIModel>> {
        const response = await this.apiGraphingGetKPIGraphsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
